### PR TITLE
Updated python code for sample weather data script

### PR DESCRIPTION
**Pull request by CharlesCalzia**
I deleted the key and changed it to a key.txt. The API key goes inside the key.txt file and then the python script can be run. It will print the current temperature, wind speed and weather status.

### CODE REVIEW

**Comment by zst-c** [comment]
you'll need to add key.txt and any other key files to your gitignore - even though they're empty and then retry, as GitGuardian is unhappy with them (due to their names!).

**Comment by CharlesCalzia** [comment]
Ok, thank you. I will add a gitignore and then add key.txt.

**Comment by zst-c** [comment]
@Computing-tech it may be worth trying to force the files to wind back (i.e. try using git push --force if you're using git) as this will stop GitHub from requiring you to have a fast-forward merge

**Comment by CharlesCalzia** [comment]
Ok, so do I type that in terminal with any parameters? And should I leave the .gitignore file? Otherwise do you think it would work if I deleted this pull request and created a new one- would it then remove the key file? Thanks.

**Comment by zst-c** [comment]
So at this point it may just be easier to delete this pull request and create a new one without a key.txt file - but if not, you need to ensure you've configured git on your system and have this added as a remote repo, and use: "git push <remote name> --force" to force github to backdate the branch

**Comment by CharlesCalzia** [comment]
Ok, thanks

**Pull request closed without merging**
